### ISSUE TITLE
In which way does StringSearch work - which format is "pattern" argument?

### ISSUE THREAD

**Issue by sjPlot** [johannburkard/StringSearch#2]
I would like to use your StringSearch library in one of my projects, however, I'm not sure how to implement it?

Is argument `pattern` allowed to be a regular expression? Let's say, I have a normal text string (lorem ipsum...) and I would like to see whether `text` contains both _lorem_ and _ipsum_. How would I do this?

```
BNDM bndm = new BNDM();
String pattern = "(?=.*lorem)(?=.*ipsum)";
int result = bndm.searchString(text, pattern);
```

(maybe there is also a mistake in my regular expression, I hate regex...)

And for logical-OR, I would assume:

```
BNDM bndm = new BNDM();
String pattern = "(lorem|ipsum)";
int result = bndm.searchString(text, pattern);
```

**Comment by johannburkard** [comment]
StringSearch doesn't support regular expressions. However, if you know you only have two patterns you want to search for, you can try searching twice (or in parallel if your environment permits). Depending on the length of the text, StringSearch may be faster.

**Comment by sjPlot** [comment]
Ah, ok. Thank you, I'll try that!
